## Q1. Pandas Version
```
What version of Pandas did you install?
```

In [3]:
# importing pandas
import pandas as pd
import numpy as np

In [4]:
pd.__version__

'3.0.3'

#### Answer: The Pandas Version is 3.0.3

## Q2. Records count
```
How many records are in the dataset?
```

In [5]:
# Target a folder named 'data_folder' inside your current directory
file_path = "C:/Users/doyin/Documents/Machine Learning Zoomcamp 2026/Module 1/car_fuel_efficiency_2026.csv"

In [6]:
# Load the CSV file into a DataFrame
df = pd.read_csv(file_path)
df.head(5)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  str
 2   fuel_type            10000 non-null  str
 3   drivetrain           10000 non-null  str
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 1.1 MB

#### Answer: There are 10,000 records in the datasets

## Q3. Fuel types
```
How many fuel types are presented in the dataset?
```

In [8]:
df.fuel_type.nunique()

3

#### Answer: There are 3 fuel types present in the dataset

## Q4. Missing values
```
How many columns in the dataset have missing values?
```

In [9]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

#### Answer: There are 2 columns (horsepower and acceleration ) with missing values

## Q5. Max fuel efficiency
```
What's the maximum fuel efficiency of cars from Asia?
```

In [10]:
df[
    df['origin'] == 'Asia'
]['fuel_efficiency_mpg'].max()

np.float64(41.2)

#### Answer: 41.2

## Q6. Median value of horsepower
```
1. Find the median value of the horsepower column in the dataset.
2. Next, calculate the most frequent value of the same horsepower column.
3. Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
4. Now, calculate the median value of horsepower once again.
```

In [11]:
# 1. Find the median value of the horsepower column
median_before = df['horsepower'].median()
median_before

np.float64(254.0)

In [12]:
# 2. Calculate the most frequent value (the mode)
# .mode() returns a Series, so [0] extracts the top frequent value
df['horsepower'].mode()[0]

np.float64(252.0)

In [13]:
# 3. Fill missing values with the most frequent value
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode()[0])

In [14]:
# 4. Calculate the median value of horsepower once again
median_after = df['horsepower'].median()
median_after

np.float64(252.0)

#### Answer: Yes, It decrease from 254.0 to 252.0

## Q7. Sum of weights
```
1. Select all the cars from Asia
2. Select only columns vehicle_weight and model_year
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it x .
5. Compute matrix-matrix multiplication between the transpose of x and x . To get the transpose, use x.T . Let's call the result XTX.
6. Invert XTX .
7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200] .
8. Multiply the inverse of xTx with the transpose of x , and then multiply the result by y. Call the result w .
9. What's the sum of all the elements of the result?
```

##### 1. Select all the cars from Asia

In [18]:
asia = df[df["origin"] == "Asia"]
asia

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

##### 2. Select only vehicle_weight and model_year

In [25]:
asia = asia[["vehicle_weight", "model_year"]]
asia

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

##### 3. Select the first 7 values

In [26]:
asia.head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

##### 4. Get the underlying NumPy array

In [27]:
x = asia.head(7).values
x

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

##### 5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [30]:
XTX = x.T @ x
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

##### 6. Invert XTX

In [32]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

##### 7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].

In [33]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

##### 8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [35]:
w = XTX_inv @ x.T @ y
w

array([0.13644777, 0.2327492 ])

##### 9. What's the sum of all the elements of the result?

In [36]:
print(w.sum())

0.36919696904927746

##### The sum of weight is 0.369